// Insert your network credentials
#define WIFI_SSID "REPLACE_WITH_YOUR_SSID"
#define WIFI_PASSWORD "REPLACE_WITH_YOUR_PASSWORD"

// Insert Firebase project API Key
#define API_KEY "REPLACE_WITH_YOUR_FIREBASE_PROJECT_API_KEY"

// Insert RTDB URL define the RTDB URL */
#define DATABASE_URL "REPLACE_WITH_YOUR_FIREBASE_DATABASE_URL" 

//Insert User Mail and Password für Firebase
#define USER_EMAIL "REPLACE_WITH_YOUR_FIREBASE_DATABASE_EMAIL_ADDRESS"
#define USER_PASSWORD "REPLACE_WITH_YOUR_FIREBASE_DATABASE_Password"